# Generated by Django 4.2.1 on 2023-07-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('hours_of_support', models.CharField(max_length=255)),
                ('award_and_certifications', models.CharField(max_length=255)),
            ],
        ),
    ]
