# Generated by Django 4.2.1 on 2023-07-25 00:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0002_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='brief_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
