# Generated by Django 4.2.1 on 2023-07-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0003_alter_experience_brief_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('graphics', 'graphics'), ('webapp', 'webapp'), ('others', 'others')], max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='Portfolio')),
            ],
        ),
    ]
