# Generated by Django 5.1.4 on 2024-12-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0005_alter_client_quote_alter_portfolio_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='link',
            new_name='brief_description',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
